# Generated by Django 4.2.2 on 2023-08-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_agregacion_de_relacion_y_campos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='f_vencimiento',
        ),
    ]
